const Discord = require('discord.js');
exports.run = function(client, message) {
    message.channel.send("konsol logları temizlendi").then(msg => {
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(" ");
    });
};
exports.conf = {
  enabled: true, 
  guildOnly: false, 
  aliases: [],
  permLevel: 4
};
exports.help = {
  name: 'logtemizle', 
  description: 'logları temizler botun pingini azaltır',
  usage: 'logtemizle'
};